### ISSUE TITLE
To add `cache` to workflows using `actions/setup-node`

### ISSUE THREAD

**Issue by oscard0m** [actions/download-artifact#102]
## Description

Add `cache` to workflows using `actions/setup-node`

## Context

`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

**Comment by Duongxuantuan2345** [comment]
> ## Sự miêu tả
> Thêm `cache`vào quy trình công việc bằng cách sử dụng`actions/setup-node`
> 
> ## Định nghĩa bài văn
> `setup-node` GitHub Action vừa phát hành một tùy chọn mới để thêm bộ nhớ cache vào các bước sử dụng nó.
> 
> Bạn có thể tìm thấy thông tin chi tiết tại đây: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
