### ISSUE TITLE
Feature request: an output containing the path to extracted artifacts

### ISSUE THREAD

**Issue by cevich** [actions/download-artifact#11]
Given that the 'path' is optional input (it may come from the upload action), it would be nice if this action provided an output 'path'.  This would reduce duplication of data in subsequent steps, which have no knowledge of inputs passed to the step containing the upload action.

**Comment by lovasoa** [comment]
Hello,
  Nice to hear that the feature is being considered. Option number 3 sounds like the most reasonable to me, as long as the behavior is properly documented.

**Comment by konradpabjan** [comment]
Done!

https://github.com/actions/download-artifact#download-path-output

I opted for option number 3. If all artifacts are downloaded at once, users just need to be aware of the extra directory is created for each artifact.
