### ISSUE TITLE
[bug] Random 503 response code has been received while attempting to download an artifact

### ISSUE THREAD

**Issue by jsobell** [actions/download-artifact#132]
### What happened?

When attempting to deploy to locally hosted Windows machines (`runs-on: [self-hosted,DEV]`) a 503 error randomly occurs, making deployment a hit and miss operation. Re-running the process sometimes passes, and sometimes fails on a different file.

```
...
Total file count: 584 ---- Processed file #519 (88.8%)
Total file count: 584 ---- Processed file #523 (89.5%)
A 503 response code has been received while attempting to download an artifact
Exponential backoff for retry #1. Waiting for 6253 milliseconds before continuing the download
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, open 'C:\CompanyName\DesktopEditor\ru\System.Xaml.resources.dll'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\CompanyName\\DesktopEditor\\ru\\System.Xaml.resources.dll'
}
```

### What did you expect to happen?

The process to attempt to retry the file transfer

### How can we reproduce it?

Not sure, as it's random, and may or may not be related to the OS.

### What version of the action are you using?

@v2

### What are your runner environments?

self-hosted, window

**Comment by konradpabjan** [comment]
v4 download artifact was recently released and it has a host of improvements. The functionality and implementation has completely changed and this issue should no longer happen: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over to v4!
