### ISSUE TITLE
List Artifacts - Attempt 5 of 5 failed with error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by nibanks** [actions/download-artifact#133]
### What happened?

A couple times a week, I see this failure in our GitHub Actions when trying to upload results. For instance:

https://github.com/microsoft/msquic/runs/5040224987?check_suite_focus=true
```
Starting download for bin
List Artifacts - Attempt 1 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
List Artifacts - Attempt 2 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
List Artifacts - Attempt 3 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
List Artifacts - Attempt 4 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
List Artifacts - Attempt 5 of 5 failed with error: connect ETIMEDOUT 13.107.42.16:443
Error: List Artifacts failed: connect ETIMEDOUT 13.107.42.16:443
```

Might be related to https://github.com/actions/upload-artifact/issues/292.

### What did you expect to happen?

The artifacts should be successfully downloaded.

### How can we reproduce it?

This GitHub action occasionally repro's it: https://github.com/microsoft/msquic/actions/workflows/wan-perf.yml

### Anything else we need to know?

Our action runs a lot of parallel jobs that might be making the issue worse.

### What version of the action are you using?

actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869

### What are your runner environments?

window

**Comment by konradpabjan** [comment]
v4 download artifact was recently released and it has a host of improvements. The functionality and implementation has completely changed and this issue should no longer happen: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over to v4!
