### ISSUE TITLE
[bug] Download path output not registered in `action.yml`

### ISSUE THREAD

**Issue by zbernstein68** [actions/download-artifact#153]
### What happened?

The `outputs.download-path` parameter [mentioned in the README](https://github.com/actions/download-artifact#download-path-output) is not registered in `action.yml`.

This means that linters such as [actionlint](https://github.com/rhysd/actionlint) will throw an error if you attempt to use it.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/67074922/162256113-ecfa91bf-0633-4f2d-bfe6-c8e7c4d2199b.png">

### What did you expect to happen?

The `action.yml` file to match the documentation

### How can we reproduce it?

N/A

### What version of the action are you using?

v3

### What are your runner environments?

linux

**Comment by iacabezasbaculima** [comment]
I faced the same problem and currently the best way to avoid the error is to pass the `-ignore <REGEX_PATTERN>` flag to `actionlint`, [read more here](https://github.com/rhysd/actionlint/blob/main/docs/usage.md#ignore-some-errors).

Nevertheless, it would be useful to add `download-path` to outputs in `action.yml`.

**Comment by bflad** [comment]
Submitted: https://github.com/actions/download-artifact/pull/194
