### ISSUE TITLE
[feat req] support name filter

### ISSUE THREAD

**Issue by mikesongming** [actions/download-artifact#165]
### What would you like to be added?

wild card filter in input parameter "name"

for example, if first upload multiple versions of artifacts as:

>      - uses: actions/upload-artifact@v3
>        with:
>          name: my_tag_${version}
>          path: ${artifact_path}

then, we hope to download alll the artifacts using wild card filter:

>       - uses: actions/download-artifact@v3
>         with:
>           name: my_tag-*

### Why is this needed?

batch download artifacts using wild card filtering

**Comment by abitrolly** [comment]
Looks like #103

**Comment by vmjoseph** [comment]
Closed with the merging of https://github.com/actions/download-artifact/pull/259
