### ISSUE TITLE
report on how many ephemeral runner provisioned by controller  

### ISSUE THREAD

**Issue by roshvin** [actions/download-artifact#169]
### What would you like to be added?

we are using action runner controller at GHE enterprise level and some users are using this ephemeral runner.
now we are looking for a report on how many ephemeral runners are provisioned at enterprise level by ARC controller so that we know the usage or how many workflows are exicuted by this runners.

is there any option even manually to get number of runners provisioned by the controller per day checking some logs ?

thanks for your support.

### Why is this needed?

we are using action runner controller at GHE enterprise level and some users are using this ephemeral runner.
now we are looking for a report on how many ephemeral runners are provisioned at enterprise level by ARC controller so that we know the usage or how many workflows are exicuted by this runners.

is there any option even manually to get number of runners provisioned by the controller per day checking some logs ?

thanks for your support.

**Comment by konradpabjan** [comment]
Closing as off-topic

For actions runner controller questions I recommend opening an issue here: https://github.com/actions/actions-runner-controller
