### ISSUE TITLE
[feat req]

### ISSUE THREAD

**Issue by vyjadhav1** [actions/download-artifact#181]
### What would you like to be added?

while working on one of pipelines got below warning

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Artifact download has finished successfully

assuming new set-output command changes done in github actions, please update download-artifact action with new changes

### Why is this needed?

to avoid warning messages

**Comment by eine** [comment]
Ref: #178

**Comment by pluma** [comment]
It's a bit silly that the latest version of an official action published by GitHub generates warnings when actually using it. Can this be fast tracked?

**Comment by pluma** [comment]
That's actually worse. What's the point of having GitHub publish actions if they don't even maintain them?

**Comment by millerick** [comment]
> That's actually worse. What's the point of having GitHub publish actions if they don't even maintain them?

@konradpabjan can you comment on whether or not this and the corresponding upload action will be maintained going forward?

**Comment by konradpabjan** [comment]
Closing, this was fixed a while back ago
