### ISSUE TITLE
[bug] Action references `actions/checkout@v2` instead of `actions/checkout@v3`

### ISSUE THREAD

**Issue by jsoref** [actions/download-artifact#186]
### What happened?

This repository's workflows and README.md use `actions/checkout@v2`

which as of September triggers a warning:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

### What did you expect to happen?

Reference actions/checkout@v3 c.f. https://github.com/actions/checkout/pull/708

### How can we reproduce it?

https://github.com/actions/download-artifact/actions/runs/3249446171

[CodeQL-Build](https://github.com/actions/download-artifact/actions/runs/3249446171/jobs/5331858453)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, github/codeql-action, github/codeql-action, github/codeql-action, github/codeql-action, github/codeql-action, actions/checkout

### Anything else we need to know?

While you're fixing things, you should probably address this:

[CodeQL-Build](https://github.com/actions/download-artifact/actions/runs/3249446171/jobs/5331858453#step:5:57)
CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

### What version of the action are you using?

v2

### What are your runner environments?

linux

**Comment by konradpabjan** [comment]
All our workflows have been updated to use the latest version of checkout in addition to using the latest versions of the codeql actions
