### ISSUE TITLE
[Bug] Artifact download progress remains 0% throughout  

### ISSUE THREAD

**Issue by L1ghtmann** [actions/download-artifact#190]
### What happened?

When downloading an artifact(s) the progress percentage remains 0 despite the download occurring as expected. 

### What did you expect to happen?

The percent to update as the download progresses.

### How can we reproduce it?

Download an artifact(s) and observe the progress percent in the log. 

### Anything else we need to know?

![download ](https://user-images.githubusercontent.com/67040127/201373595-8adf13a8-e37a-46a4-a54c-deb15cb6abdd.png)

### What version of the action are you using?

v3.0.1

### What are your runner environments?

linux, macos

**Comment by cm-henrikw** [comment]
We are experiencing the very same issue for only a few days, everything was well before. Additionally, we run into a timeout for a specific IP. It does not matter if we run this on self-hosted or GitHub hosted runners.

```
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
An error occurred while attempting to download a file
Error: connect ETIMEDOUT 13.107.42.16:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.107.42.16',
  port: 443
}
Exponential backoff for retry #1. Waiting for 4802 milliseconds before continuing the download
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
Total file count: 1 ---- Processed file #0 (0.0%)
```

**Comment by konradpabjan** [comment]
V4 download-artifact has recently shipped with a host of improvements. The logging behavior is also different: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over to v4:
