### ISSUE TITLE
[feat req] Downloading more than one, but not all, artifacts

### ISSUE THREAD

**Issue by dhruvkb** [actions/download-artifact#212]
### What would you like to be added?

It would be nice if there was a way to specify an arbitrary list of artifact names to download, instead of choosing between one specific artifact and all of them.

### Why is this needed?

In our CI pipeline, we have six artifacts built in one job with subsequent jobs needing somewhere between two to three of these at a time. Currently we are using multiple steps to download these artifacts individually, whereas passing a list encoded in JSON like '["artifact_a", "artifact_b"]' would be reduce this to one step and, if the action supports, also speed things up with parallelisation, which is currently not possible because of sequential steps.

**Comment by gorohash** [comment]
It seems to be duplicated as https://github.com/actions/download-artifact/issues/6#issuecomment-620634668

**Comment by dhruvkb** [comment]
@gorohash thanks for pointing that out. Also yes, you're right that there's an overlap between the two issues. I'll update my use-case and workaround there, and close this.
