### ISSUE TITLE
download artifact not working in docker image

### ISSUE THREAD

**Issue by pzim** [actions/download-artifact#22]
Hi, I am attempting to use the download/upload actions to share data between 2 jobs in a workflow. Both jobs are triggered based on a user-entered pull-request comment. The first job uploads 2 files (successfully), but the second job fails to download the 2 files. 

This workflow is running in a docker image using the Github runners.

![image](https://user-images.githubusercontent.com/737760/75902297-0a59fc80-5dfd-11ea-8e08-28c0bf4bd967.png)

Here is the failed run output:

![image](https://user-images.githubusercontent.com/737760/75902407-2f4e6f80-5dfd-11ea-8e09-3cdc3397e0b1.png)

I've been iterating on this with no luck. Here is the workflow file:

```jobs:
  kops-apply-changes:
    name: Kops Apply Changes
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/kops-apply-updates'
    
    steps:
      - uses: actions/checkout@v2
      - name: Apply Kops Changes
        id: kops_changes_update_apply
        uses: ./github-actions/kops-update-changes-action
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          kops_update_action: 'update-apply'
      - run: echo ${{ steps.kops_changes_update_apply.outputs.cluster_name }} > kops_cluster.out
      - run: echo ${{ steps.kops_changes_update_apply.outputs.kops_state }} > kops_state.out
      - uses: actions/upload-artifact@v1
        with:
          name: cluster_name
          path: kops_cluster.out
      - uses: actions/upload-artifact@v1
        with:
          name: kops_state
          path: kops_state.out

  rolling-update:
    name: Kops Apply Rolling Updates
    runs-on: ubuntu-latest
    if: github.event.comment.body == '/kops-apply-rolling-updates'
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: cluster_name
          path: ${{ github.workspace }}/kops_cluster.out
      - uses: actions/download-artifact@v1
        with:
          name: kops_state
          path: ${{ github.workspace }}/kops_state.out
      - shell: bash
        run: |
          cluster_name_value = `cat ${{ github.workspace }}/kops_cluster.out`
          kops_state_value = `cat ${{ github.workspace }}/kops_state.out`
        env:
          KOPS_CLUSTER: cluster_name_value
          KOPS_STATE: kops_state_value
      - name: Apply Kops Rolling Update
        id: kops_changes_update_apply
        uses: ./github-actions/kops-update-changes-action
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with: 
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          kops_update_action: 'rolling-update-apply'
          cluster_name: cluster_name_value
          kops_state: kops_state_value```

Any ideas/thoughts welcome

**Comment by konradpabjan** [comment]
Both `upload-artifact@v1` and `download-aritfact@v1` do not work correctly with containers.

Good news though is that this should now be possible with the upcoming `v2` versions of the actions 😀

You can try it out by using `actions/download-artifact@v2-preview` (see the pinned issue for more information)

Here is a similar issue related to `upload-artifact` which gives some extra information: https://github.com/actions/upload-artifact/issues/13

**Comment by ranisalt** [comment]
@konradpabjan it not only does not work, it ignores the `path` argument.

See the second (rocm-comgr) job [here](https://github.com/ranisalt/rocm-arch/runs/531714689), it reports success while clearly ignoring the `path` argument and also a following `ls -R` does not show the downloaded artifact.

**Comment by konradpabjan** [comment]
The `v2` version of `download-artifact` has been released so and issues related to downloading artifacts in containers should be fixed now (earlier bugs reported during the preview have been fixed) . You can use it now by doing `download-artifact@v2`

If there are any more issues, please let me know.
