### ISSUE TITLE
[bug] Slow/broken artifacts download

### ISSUE THREAD

**Issue by chernyadev** [actions/download-artifact#224]
### What happened?

Our CI job hangs at download. It used to work fine just yesterday. Today it takes about 60 minutes to download ~200MB artifact. 

![image](https://github.com/actions/download-artifact/assets/25583587/3fa6de83-97cd-432b-b13f-f3710091c499)

### What did you expect to happen?

Take less than an hour to donwnload 200MB artifact.

### How can we reproduce it?

We have a private repo, but this issue seems to be rather massive. Testing any workflow which utilises download-artifact action should be suffucient. 

### Anything else we need to know?

We also observe slowdown on upload. I guess that these issues might be connected:
- https://github.com/actions/upload-artifact/issues/429
- https://github.com/actions/upload-artifact/issues/428
- https://github.com/actions/upload-artifact/issues/427

### What version of the action are you using?

actions/download-artifact@v3

### What are your runner environments?

linux

**Comment by chernyadev** [comment]
![image](https://github.com/actions/download-artifact/assets/25583587/a33da00c-3e0e-4d1d-8ad8-5fada07fcf3d)

**Comment by dejanilicqa** [comment]
Same issue here, it takes too much time for downloading.
![Screenshot 2023-08-21 at 16 34 37](https://github.com/actions/download-artifact/assets/103043607/12a86b1c-e958-46eb-9066-5e8ad2a9d951)
