### ISSUE TITLE
[bug] Timeout Error while attempting to download artifacts

### ISSUE THREAD

**Issue by ranpatha** [actions/download-artifact#228]
### What happened?

Jobs at step actions/download-artifact@v3 is failing with below errors.
Total file count: 1 ---- Processed file [#0](https://support.github.com/ticket/0) (0.0%)
Total file count: 1 ---- Processed file [#0](https://support.github.com/ticket/0) (0.0%)
Total file count: 1 ---- Processed file [#0](https://support.github.com/ticket/0) (0.0%)
Total file count: 1 ---- Processed file [#0](https://support.github.com/ticket/0) (0.0%)
An error occurred while attempting to download a file
Error: connect ETIMEDOUT 20.102.36.236:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
errno: -110,
code: 'ETIMEDOUT',
syscall: 'connect',
address: '20.102.36.236',
port: 443
}
Exponential backoff for retry [#2](https://support.github.com/ticket/2). Waiting for 12622 milliseconds before continuing the download
Total file count: 1 ---- Processed file [#0](https://support.github.com/ticket/0) (0.0%)
Total file count: 1 ---- Processed file [#0](https://support.github.com/ticket/0) (0.0%)
Total file count: 1 ---- Processed file [#0](https://support.github.com/ticket/0) (0.0%)
Total file count: 1 ---- Processed file [#0](https://support.github.com/ticket/0) (0.0%)

### What did you expect to happen?

actions/download-artifact@v3 should download Artifacts which are uploaded in previous job using actions/upload-artifact@v3.

### How can we reproduce it?

The issue is same as previous issue: [Bug] Artifact download progress remains 0% throughout #190

### Anything else we need to know?

This was working before and issue started from last one month.

### What version of the action are you using?

v3

### What are your runner environments?

linux

**Comment by konradpabjan** [comment]
v4 download artifact was recently released and it has a host of improvements. The functionality and implementation has completely changed compared to v2 and v3 and this issue should no longer happen as downloads happen differently: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over to v4!
