### ISSUE TITLE
[feat req] Custom repository and run_id parameters

### ISSUE THREAD

**Issue by nibanks** [actions/download-artifact#229]
### What would you like to be added?

Allow the download of artifacts from other repositories and runs. We are trying to download artifacts in [microsoft/netperf](https://github.com/microsoft/netperf) from other partially finished workflows in other repositories, and haven't found a way to do it otherwise (tried REST API, but it didn't seem to work).

### Why is this needed?

We need one repository to be able to download another's build artifacts. We have one common repository that runs performance tests for multiple others, and needs to grab the artifacts dynamically (instead of building them all again).

**Comment by daschuer** [comment]
Just for reference, a working script that download an artifact form another repository from the same user: 
https://github.com/daschuer/mixxx/blob/b3d2e1e8a8e1a0328142bd46950e1018a47c8d70/tools/windows_buildenv.bat#L57C89-L57C100
Looking up the BUILDENV_ID is still a manual process.

**Comment by konradpabjan** [comment]
With v4 download-artifact this is now supported. You can provide a custom repository name or workflow_run ID as inputs to download artifacts from other runs.

https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories

Recommend switching over to v4 as there are a host of improvements: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Note: You have to upload artifacts with v3 in order for this to work

**Comment by jdblischak** [comment]
> Note: You have to upload artifacts with v3 in order for this to work

v4?? From the blog post you linked:

> Artifacts `v4` is not cross-compatible with previous versions. For example, an artifact uploaded using `v3` cannot be used with `actions/download-artifact@v4`.
