### ISSUE TITLE
[bug] v4: Breaking change: 0 download artifacts downloaded now exits with failure

### ISSUE THREAD

**Issue by johannesclaesson** [actions/download-artifact#251]
### What happened?

After upgrading from v3 to v4, the download artifact action now fails runs when there are no artifacts to download. In v3, it proceeded with success. This should have been marked as a breaking change, since it stops workflows.

v3 (succeeds):
```
No artifact name specified, downloading all artifacts
Creating an extra directory for each artifact that is being downloaded
Unable to find any artifacts for the associated workflow
There were 0 artifacts downloaded
Artifact download has finished successfully
```

v4 (fails):
```
No input name specified, downloading all artifacts. Extra directory with the artifact name will be created for each download
Found 0 artifact(s)
Error: Unable to download artifact(s): No artifacts found for run '<runid>' in '<repository>'
```

### What did you expect to happen?

Same exit code with both versions.

### How can we reproduce it?

Try to download non existing artifact with v3 and v4.

### What version of the action are you using?

v4

### What are your runner environments?

linux

**Comment by avasenin** [comment]
faced same. our use case - we have generic shared workflows and has download artifacts as a step to fetch possible artifacts from previous steps.

I see check was introduced here: https://github.com/actions/download-artifact/blob/main/src/download-artifact.ts#L84

Is it possible to return old behaviour?

**Comment by grische** [comment]
A side note:
I had to downgrade both upload-artifact as well as download-artifact to v3 for this to work. If you only downgrade download-artifact, you end up with `Unable to find any artifacts for the associated workflow`.

**Comment by ffineis** [comment]
Also experiencing this. Fortunately the PR to upgrade from 3 -> 4 caught the bug before we merged the suggested upgrade PR, but we're going to hold off until this is fixed or there are upgrade instructions.

**Comment by robherley** [comment]
👋 This should be fixed in the most recent release, a side effect of the fix in:
- https://github.com/actions/download-artifact/pull/259

We should have more well defined behavior once this lands:
- https://github.com/actions/download-artifact/pull/254

**Comment by johannesclaesson** [comment]
Verified. Thanks!
