### ISSUE TITLE
[feat req] Add if-no-name-found parameter 

### ISSUE THREAD

**Issue by dariocurr** [actions/download-artifact#253]
### What would you like to be added?

I tried to implement but you ignored me

- https://github.com/actions/download-artifact/pull/234

### Why is this needed?

- https://github.com/actions/download-artifact/pull/234

**Comment by robherley** [comment]
👋 @dariocurr Apologies for the delay in response.

If you open up a new PR, we'll take a look.

**Comment by dariocurr** [comment]
#254
