### ISSUE TITLE
[docs] Document unclear behavior when name: parameter is omitted

### ISSUE THREAD

**Issue by jbarlow83** [actions/download-artifact#260]
### What files would you like to change?

The readme says that the name parameter is optional but does not describe what happens when the name is omitted.

Given a download step using

```
with:
     path: dist
```

The resulting directory seems to be that each named artifact is extracted in its own directory:

```
./dist/artifact/file
```

This is surprising behavior, because when `name: artifact` is supplied, the name of the artifact is omitted:

```
./dist/file
```

### What are your suggested changes?

Extend readme documentation to describe what happens when the name is omitted, or  make name mandatory.

**Comment by konradpabjan** [comment]
In the README this is already mentioned. If the name is not provided than all artifacts are downloaded.

```
    # Name of the artifact to download.
    # If unspecified, all artifacts for the run are downloaded.
    # Optional.
    name:

```

If all artifacts are downloaded than the directory structure is a bit different by default to differentiate between all the artifacts that are being downloaded: https://github.com/actions/download-artifact?tab=readme-ov-file#download-all-artifacts

> If the name input parameter is not provided, all artifacts will be downloaded. To differentiate between downloaded artifacts, by default a directory denoted by the artifacts name will be created for each individual artifact. This behavior can be changed with the merge-multiple input parameter.

There is a `merge-multiple` input option you can specify to control this behavior (it's available only with v4 which was released recently)
