### ISSUE TITLE
[bug] Artifacts not available for followup job (v4)

### ISSUE THREAD

**Issue by cdce8p** [actions/download-artifact#281]
### What happened?

I was testing the update to `v4` when I noticed that some (created) artifacts wouldn't get downloaded in the collection / coverage report job which runs after the test matrix. In my case only 9 of 18 were found. Rerunning the coverage job, showed that now all 18 were downloaded. That suggests to me that some server-side processing needs to happen before the artifacts are actually available. Unfortunately that makes `v4` practically unusable for us, since the job would always fail the first time around.

### What did you expect to happen?

Once the `upload-artifact` steps completes, the artifact should immediately be available for download to the `download-artifact` action. If not, the `upload` step should block until that's the case / or at least have an option to do so.

### How can we reproduce it?

_Not tested but this should be enough to reproduce it._

Create a matrix with 15+ jobs which each uploads an artifact with `coverage-${{ matrix.id }}`. Add a collection job which runs `after` the "test" jobs complete and download all artifacts.
```yaml
uses: actions/download-artifact@v4.1.1
with:
  pattern: coverage-*
```

Check the output to see which artifacts were actually found / downloaded.

### What version of the action are you using?

v4.1.1

### What are your runner environments?

linux

**Comment by angelo-loria** [comment]
I'm seeing something very similar in a matrix job, will see if I can get reproducible code up somewhere

**Comment by mserwicki** [comment]
I'm also experiencing issues with the action version `v4.1.0` on `ubuntu-latest` and the failures seem to occur randomly inside matrix jobs.

**Comment by cdce8p** [comment]
@ViktorDronov That's unrelated to this issue. Note that you must either use `v3` or `v4` for both, they don't work together!

**Comment by cdce8p** [comment]
After some more investigation, it looks like the collection job was missing one of the jobs in `needs` thus not waiting for it.
