### ISSUE TITLE
Feature request: output downloaded paths in log

### ISSUE THREAD

**Issue by altendky** [actions/download-artifact#29]
Similar to #11 but I would like to be able to see the paths to the downloaded files in the log.  Perhaps the 'variable' output implemented for #11 would show up in the log and satisfy this request.  My issue is regularly apparently getting it wrong as to what to enter in the path parameter and ending up with stuff like below where the file is not found in a subsequent step and I have to either add a tmate action for debug or other debug commands or just start guessing...

![image](https://user-images.githubusercontent.com/543719/80531338-76be2b80-8968-11ea-94a6-860e603cc194.png)

**Comment by mxcl** [comment]
Alternatively some examples of what happens when you upload and download with the various parameters in the README. I’ve wasted a fair amount of time (and money) trying to figure out what happens with files vs. directories and the various configurable parameters.

**Comment by konradpabjan** [comment]
I've added some extra logging and an output parameter to help make it even easier to identify where artifacts are downloaded to. If no artifact name is specified and all artifacts get downloaded (with an extra directory created), I've also added extra logging/info to make this more obvious.

![image](https://user-images.githubusercontent.com/16109154/87537475-f2dc2b80-c69a-11ea-8e16-b4b567f7e56a.png)

If you turn on step, debugging, you can also see where each file was individually downloaded to, and how long it took each file to be downloaded. 

For all of these changes, you need to be using the `v2` version of `download-artifact`

**Comment by retorquere** [comment]
How do I turn this on? I have an 2 download-artifact's in a job where one of them doesn't seem to do anything. Multiple download-artifacts in a single job are allowed, right?
