### ISSUE TITLE
[FR] Retry on HTTP 500

### ISSUE THREAD

**Issue by webknjaz** [actions/download-artifact#33]
Here's a job that errored out when this action hit HTTP 500: https://github.com/ansible/pylibssh/runs/629834790?check_suite_focus=true#step:5:61

How about implementing a sort of exponential backoff retry strategy to possibly make the download process more robust?

**Comment by konradpabjan** [comment]
We actually have exponential backoff and retries setup, a 500 though isn't one of the retryable status codes: https://github.com/actions/toolkit/blob/57d20b4db494c25af8d2f3d9323650044610e531/packages/artifact/src/internal/utils.ts#L74

I'll add 500s to the list and then it should retry up to 5 times if an error is hit

**Comment by webknjaz** [comment]
Yeah, it was actually happening on `v2` already.

**Comment by webknjaz** [comment]
@konradpabjan got another case for retries: `##[error]connect ETIMEDOUT 13.107.42.16:443` which is the only output a failed step has in my workflow (just in one job).

https://github.com/ansible/pylibssh/runs/640533022#step:7:10

**Comment by wjrogers** [comment]
> @konradpabjan got another case for retries: `##[error]connect ETIMEDOUT 13.107.42.16:443` 

I just had a workflow run fail with this exact same error (trying to download an artifact from a previous job).

**Comment by webknjaz** [comment]
This looks like a low-level socket is getting stuck and then timing out.

**Comment by webknjaz** [comment]
FTR the same is happening with upload-artifact:
```console
Run actions/upload-artifact@v2
With the provided path, there will be 1 files uploaded
##### Begin Diagnostic HTTP information #####
Status Code: 503
Status Message: Service Unavailable
Header Information: {
  "cache-control": "no-store",
  "content-length": "228",
  "content-type": "text/html",
  "server": "Microsoft-IIS/10.0",
  "x-msedge-ref": "Ref A: 4E921A466D6E41768580DFBF79A7F107 Ref B: ATAEDGE1018 Ref C: 2020-05-07T20:08:58Z",
  "date": "Thu, 07 May 2020 20:09:02 GMT",
  "connection": "close"
}
###### End Diagnostic HTTP information ######
##[error]Unable to create a container for the artifact dist-wheel-macOS-python2.7 at https://pipelines.actions.githubusercontent.com/cC5s7csFV8PcrlweNRWx6PDHHyvYCGGwuLa0yo6ROPMTVelxBD/_apis/pipelines/workflows/98515921/artifacts?api-version=6.0-preview
```
https://github.com/ansible/pylibssh/runs/654300467?check_suite_focus=true#step:21:25

**Comment by boredland** [comment]
Just had `##[error]connect ETIMEDOUT 13.107.42.16:443` in `actions/download-artifact@v2`. Funny enough I moved over here from actions/cache because of the similar actions/cache#208

**Comment by konradpabjan** [comment]
@boredland thanks for the notice. Haven't come across that error. Can you open another issue here. Fixing that will probably require some extra work.

**Comment by webknjaz** [comment]
@konradpabjan FYI I linked the related log above: https://github.com/ansible/pylibssh/runs/640533022#step:7:10

**Comment by konradpabjan** [comment]
Some work was recently done behind the scenes to address 500s being returned (most were caused by timeouts on our end). Now a 503 should be returned and the download will be retried by the action up to 5 times.

If 500s continue to appear, please ping me or create a new issue.
