### ISSUE TITLE
[bug] Suddenly cannot download artifacts

### ISSUE THREAD

**Issue by kabir** [actions/download-artifact#351]
### What happened?

Since Sunday I've been having problems downloading artifacts from another job. I am getting this message:
```
Run actions/download-artifact@v4
Downloading single artifact
Error: Unable to download artifact(s): Artifact not found for name: .job-env
        Please ensure that your artifact is not expired and the artifact was uploaded using a compatible version of toolkit/upload-artifact.
        For more information, visit the GitHub Artifacts FAQ: https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md
```
See https://github.com/wise-agents/wise-agents/actions/runs/10697954701/job/29656263427 which has a link to the [workflow file](https://github.com/wise-agents/wise-agents/actions/runs/10697954701/workflow#L49-L53).

This workflow handles the `workflow_run` event, and here is the  yaml doing the download
```
   - uses: actions/download-artifact@v4
      with:
        name: .job-env
        github-token: ${{ github.token }}
        run-id: ${{ github.event.workflow_run.id }}
```

The workflow triggering this can be found here https://github.com/wise-agents/wise-agents/actions/runs/10689604921/workflow and uploads the artifact:

```
 - uses: actions/upload-artifact@v4
      with:
        name: .job-env
        path: .job-env
````        

### What did you expect to happen?

Although this is quite a new repository for which we implemented these workflows quite recently, I am assuming that since it worked last week after lots of reading of the documentation, that there is an issue on the GitHub Actions side?

### How can we reproduce it?

You can reproduce it by pushing or opening a PR, which will trigger this workflow https://github.com/wise-agents/wise-agents/blob/main/.github/workflows/build-and-test-trigger.yml.  Once that is complete, the `workflow_run` workflow at https://github.com/wise-agents/wise-agents/blob/main/.github/workflows/build-and-test-workflow-run.yml will trigger.

### Anything else we need to know?

We have an older repository where we have been doing something similar, although with another mechanism. This also started failing around the same time as this repository.

Here the 'trigger' workflow is https://github.com/wildfly/wildfly/blob/main/.github/workflows/dep-diff-pull_request.yml#L188-L191 and does
```
      - uses: actions/upload-artifact@v4
        with:
          name: input-artifacts
          path: ${{ steps.prepare.outputs.artifacts }}
```

The `workflow_run` part uses the script plugin to download the artifact https://github.com/wildfly/wildfly/blob/main/.github/workflows/dep-diff-workflow_run.yml#L27-L50
```
      - name: Download artifacts
        # It would have been nice to be able to use actions/download-artifact@v2
        # for this, but as the artifacts are uploaded by another workflow it does
        # not seem possible - so we need to do this stuff instead
        uses: actions/github-script@v7.0.1
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            console.log(artifacts);
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "input-artifacts"
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/input.zip', Buffer.from(download.data));
```
This mechanism has been working for years, and no updates have been made to either of the workflows in the past six months.

Here the errror can be seen e.g. in https://github.com/wildfly/wildfly/actions/runs/10697979078/job/29656342290:
```
Run actions/github-script@v7.0.1
{
TypeError: Cannot read properties of undefined (reading 'id')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v7.0.1/dist/index.js:35424:16), <anonymous>:15:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/runner/work/_actions/actions/github-script/v7.0.1/dist/index.js:35522:20)
  status: 200,
  url: 'https://api.github.com/repos/wildfly/wildfly/actions/runs/10690625723/artifacts',
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    'cache-control': 'private, max-age=60, s-maxage=60',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 04 Sep 2024 08:28:12 GMT',
    etag: 'W/"41988a4eebfffdb362d95814341c0f0ba28013fae9211531d86be807ad54ec49"',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'github.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept, Authorization, Cookie, X-GitHub-OTP,Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-github-permissions': 'actions=read',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-api-version-selected': '2022-11-28',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'B801:8E602:95A16E0:11F26CDA:66D81A1C',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4999',
    'x-ratelimit-reset': '1725442092',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '1',
    'x-xss-protection': '0'
  },
  data: { total_count: 0, artifacts: [] }
}
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'id')
```

So, I suspect there could be something going wrong in how GitHub Actions handles artifacts at the moment, since both repositories started failing around last weekend?

If not, I would love to hear how I can fix this on my side!

### What version of the action are you using?

v4

### What are your runner environments?

linux

**Comment by neutrinoceros** [comment]
I had a similar problem, and found that it was caused by a documented breaking change in `upload-artifact@v4`, see https://github.com/actions/upload-artifact/releases/tag/v4.4.0

**Comment by kabir** [comment]
@neutrinoceros - thank you! Will try it out in a second and report back :-)
