### ISSUE TITLE
Deprecation notice: v3 of the artifact actions

### ISSUE THREAD

**Issue by yacaovsnc** [actions/download-artifact#358]
>Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible.

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

**Comment by arminrosu** [comment]
@yacaovsnc Has this v4 bug been fixed? https://github.com/actions/download-artifact/issues/294

**Comment by SrRyan** [comment]
Hi @arminrosu if you still require assistance please seek out help within this [discussion](https://github.com/orgs/community/discussions/142581) or file a support ticket. Thanks!

**Comment by arminrosu** [comment]
@SrRyan thanks, the issue seems to have been resolved, or at least I haven't encountered it again. Would have been nice to get a timely answer, generally I must say the responsiveness on issues is 0.
