### ISSUE TITLE
Add support for tilde expansion

### ISSUE THREAD

**Issue by phil-opp** [actions/download-artifact#37]
The `upload-artifact` action supports [tilde expansion](https://github.com/actions/upload-artifact#environment-variables-and-tilde-expansion), i.e. it substitutes `~` with `$HOME`. The `download-artificat` action, however, does not seem to support it. This is a bit surprising because I would expect that using the same path for upload and download would restore the file to the same location.

**Comment by mogifiguer** [comment]
por favor  ajuda-me como posso  contribuir  não  quer ficar no anonimato quero  pagar com pequena  quantia
