### ISSUE TITLE
Hi @tarcila, the bug is due to the fact that there are two folders both with files different only in their casing:

### ISSUE THREAD

**Issue by alirezajon** [actions/download-artifact#48]
Hi @tarcila, the bug is due to the fact that there are two folders both with files different only in their casing:
`/installed/x64-linux/share/Catch2`
`/installed/x64-linux/share/catch2`

It seems that the download-artifact action is creating only one of the folders thinking the other one is the same.  We're looking into how best fix this issue.

_Originally posted by @lkillgore in https://github.com/actions/download-artifact/issues/12#issuecomment-561863622_

**Comment by konradpabjan** [comment]
I've responded to the original issue: https://github.com/actions/download-artifact/issues/12#issuecomment-667276060
