### ISSUE TITLE
Github community link on the template

### ISSUE THREAD

**Issue by llrs** [actions/download-artifact#67]
The link on the template for issues to GiHub Community Forum's Actions Board (https://github.community/t5/GitHub-Actions/bd-p/actions) is not reachable to regular users like me. Maybe it changed https://github.community/c/github-actions/41 ?

(I was about to open an issue here but I finally opened a [question there](https://github.community/t/download-artifact-doesnt-find-existing-artifact/144291), hope to understand what I might be missing.)

**Comment by konradpabjan** [comment]
Fixed as part of https://github.com/actions/.github/pull/23
