### ISSUE TITLE
Bug: Can't Use this Action due to "event.js" exception thrown

### ISSUE THREAD

**Issue by RedHoodedWraith** [actions/download-artifact#74]
Hi,

I am getting the following error everytime I try to download an artifact that was previously uploaded. The artifact meant to be downloaded is a directory filled with contents.

```
Run actions/download-artifact@v2
  with:
    name: je-build
Starting download for je-build
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 40
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '/home/runner/work/[repo name]/[repo name]/[folder in repo]'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:294:12
    at FSReqCallback.oncomplete (fs.js:146:23) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/home/runner/work/[repo name]/[repo name]/[folder in repo]'
```

I've ommited the names of my repo. I tried looking for the `event.js` file in the repo for _actions/download-artifact@v2_ however I couldn't find it. Does anyone know how to fix this? It appears to be some backend issue.

Kind Regards,

Rowan

**Comment by konradpabjan** [comment]
Could you enable step debugging, there should be some extra information: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging

Are you also using `upload-artifact@v2` or `v1`?

**Comment by RedHoodedWraith** [comment]
Hi, I was using `upload-artifact@v2`. Switching to `upload-artifact@v1` fixed the issue. I will get back to you about the debug results

**Comment by eggplants** [comment]
Same error has happened to me.

Actual Log:
https://github.com/eggplants/rendakun.py/actions/runs/3776407581/jobs/6419672990#step:4:1

```txt
Starting download for rendakun-macos
Directory structure has been setup for the artifact
Total number of files that will be downloaded: 1
node:events:36[8](https://github.com/eggplants/rendakun.py/actions/runs/3776407581/jobs/6419672990#step:4:9)
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, open '/home/runner/work/rendakun.py/rendakun.py/rendakun'
Emitted 'error' event on WriteStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:[12](https://github.com/eggplants/rendakun.py/actions/runs/3776407581/jobs/6419672990#step:4:13)2:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: '/home/runner/work/rendakun.py/rendakun.py/rendakun'
}
```

Archived Full Log:
https://gist.github.com/eggplants/f933f02fd47e410288e1821d27c49905

**Comment by eggplants** [comment]
When I reverted from v3 to v1 (https://github.com/eggplants/rendakun.py/commit/61f9865ea5729eafec94b10da8bb1881e66c261d), `actions/download-artifact` finished successfully. 
https://github.com/eggplants/rendakun.py/actions/runs/3776459210

**Comment by konradpabjan** [comment]
v4 download artifact was recently released and it has a host of improvements. The functionality and implementation has completely changed compared to v2 and v3 and this issue should no longer happen: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Recommend switching over to v4!
